const menu = [
  {
    id: 1,
    title: 'Hamburger',
    category: 'hamburger',
    price: 1.50,
    img: './images/item1.jpg',
    desc: `Hamburgers are traditionally made with ground beef and served with onions, tomatoes, lettuce, ketchup, and other garnishes. `,
  },
  {
    id: 2,
    title: 'Pizza Margarita',
    category: 'pizza',
    price: 1.50,
    img: './images/item2.jpg',
    desc: `pizza some combination of olive oil, oregano, tomato, olives, mozzarella or other cheese, and many other ingredients..`,
  },
  {
    id: 3,
    title: 'Coca Cola',
    category: 'pijet',
    price: 0.99,
    img: './images/item3.jpg',
    desc: `Pijet freskuese.... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...  `,
  },
  {
    id: 4,
    title: 'Pasta Bolognese ',
    category: 'pasta',
    price: 2.5,
    img: './images/item4.jpg',
    desc: `Spaghetti bolognese consists of spaghetti with an Italian ragù (meat sauce) made with minced beef, bacon and tomatoes, served with Parmesan cheese. , `,
  },
  {
    id: 5,
    title: 'Torte me dredhëz',
    category: 'Torte ',
    price: 3.00,
    img: './images/item5.jpg',
    desc: `strawberry shortcake is a biscuit with whipped cream and fresh strawberries.`,
  },
  {
    id: 6,
    title: 'Chicken Burger ',
    category: 'hamburger',
    price: 1.99,
    img: './images/item6.jpg',
    desc: `hamburger (grilled/broiled ground meat patty) made from ground chicken, which is the only time it would actually be a “chicken burger.”`,
  },
  {
    id: 7,
    title: 'Caj',
    category: 'pijet',
    price: 0.99,
    img: './images/item7.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Hot Chocolate',
    category: 'pijet',
    price: 1.99,
    img: './images/item8.jpg',
    desc: `Hot chocolate, heated milk or water, and usually a sweetener like whipped cream or marshmallows. `,
  },
  {
    id: 9,
    title: 'File pule',
    category: 'dreka',
    price: 2.99,
    img: './images/item9.jpg',
    desc: `File Pule pa salcë. File Pule me salcë këpurdhash. File Pule me salcë Escalopo. File Pule me salcë portokalli. .`,
  },
  {
    id: 10,
    title: 'pica me kërpudha',
    category: 'pizza',
    price: 1.50,
    img: './images/item10.jpg',
    desc: ` Mushroom & Herb Pizza, the crust is light, crispy and oh so flavorful. The mushrooms are earthy, plump, and a bit ...`,
  },
  {
    id: 11,
    title: 'Hot Chocolate',
    category: 'pijet',
    price: 1.99,
    img: './images/item8.jpg',
    desc: `Hot chocolate, heated milk or water, and usually a sweetener like whipped cream or marshmallows. `,
  },
];
export default menu;
